ALTER TABLE `oxmanufacturers` ADD `OXLONGDESC` TEXT NOT NULL AFTER `OXSHORTDESC`;
ALTER TABLE `oxmanufacturers` ADD `OXLONGDESC_2` TEXT NOT NULL AFTER `OXSHORTDESC_2`;
ALTER TABLE `oxmanufacturers` ADD `OXLONGDESC_3` TEXT NOT NULL AFTER `OXSHORTDESC_3`; 
