ALTER TABLE `oxmanufacturers` ADD `EXTLONGDESC` TEXT NOT NULL AFTER `OXSHORTDESC`;
ALTER TABLE `oxmanufacturers` ADD `EXTLONGDESC_2` TEXT NOT NULL AFTER `OXSHORTDESC_2`;
ALTER TABLE `oxmanufacturers` ADD `EXTLONGDESC_3` TEXT NOT NULL AFTER `OXSHORTDESC_3`; 
